<ivy-module version="2.0" xmlns:ea="http://www.easyant.org">
    <info organisation="io.restx" module="restx-md-testing" revision="0.35" status="integration">
        <ea:build organisation="org.apache.easyant.buildtypes" module="build-std-java" revision="0.9"
            compile.java.source.version="1.7"
            compile.java.target.version="1.7"
        />
    </info>
    <configurations>
        <conf name="default"/>
        <conf name="runtime"/>
        <conf name="test"/>
    </configurations>
    <publications>
        <artifact type="jar"/>
    </publications>
    <dependencies>
        <dependency org="junit" name="junit" rev="4.11" conf="test->default" />
        <dependency org="io.restx" name="restx-build-testing" rev="1.0-rc1" conf="test->default" />
        <dependency org="io.restx" name="restx-md-fragments" rev="0.35-rc3" conf="test->default" />
    </dependencies>
</ivy-module>
