<ivy-module version="2.0" xmlns:ea="http://www.easyant.org">
    <info organisation="io.restx" module="restx-md-testing" revision="0.35-rc4" status="integration">
        <ea:build organisation="org.apache.easyant.buildtypes" module="build-std-java" revision="0.9"
            compile.java.source.version="1.7"
            compile.java.target.version="1.7"
        />
    </info>
    <configurations>
        <conf name="default"/>
        <conf name="runtime"/>
        <conf name="test"/>
    </configurations>
    <publications>
        <artifact type="jar"/>
    </publications>
    <dependencies>
        <dependency org="io.restx" name="restx-build" rev="1.0-rc1" conf="default" />
        <dependency org="io.restx" name="restx-common" rev="0.35-rc4" conf="default" />
        <dependency org="junit" name="junit" rev="4.11" conf="default" />
        <dependency org="org.assertj" name="assertj-core" rev="1.6.0" conf="default" />
        <dependency org="org.apache.maven.shared" name="maven-verifier" rev="${maven-verifier.version}" conf="default" />
        <dependency org="com.googlecode.junit-toolbox" name="junit-toolbox" rev="${junit.toolbox.version}" conf="default" />
        <dependency org="io.restx" name="restx-md-fragments" rev="0.35-rc4" conf="default" />
    </dependencies>
</ivy-module>
