#! /usr/bin/env sh

PRG="$0"
while [ -h "$PRG" ] ; do
  PRG=`readlink "$PRG"`
done

dir=`dirname $PRG`

while [ 1 ]; do
  if [ -f "$dir/upgrade.sh" ]; then
    sh "$dir/upgrade.sh"
    rm -f "$dir/upgrade.sh"
  fi

  sh "$dir/launch.sh"

  if [ -f "$dir/.restart" ]; then
     rm -f "$dir/.restart"
  else
    break
  fi
done

