<ivy-module version="2.0" xmlns:ea="http://www.easyant.org">
    <info organisation="io.restx" module="restx-specs-tests" revision="0.35" status="integration">
        <ea:build organisation="org.apache.easyant.buildtypes" module="build-std-java" revision="0.9"
            compile.java.source.version="1.7"
            compile.java.target.version="1.7"
        />
    </info>
    <configurations>
        <conf name="default"/>
        <conf name="runtime"/>
        <conf name="test"/>
    </configurations>
    <publications>
        <artifact type="jar"/>
    </publications>
    <dependencies>
        <dependency org="io.restx" name="restx-factory" rev="0.35" conf="default" />
        <dependency org="io.restx" name="restx-core" rev="0.35" conf="default" />
        <dependency org="io.restx" name="restx-core-annotation-processor" rev="0.35" conf="default" />
        <dependency org="junit" name="junit" rev="4.11" conf="default" />
        <dependency org="org.assertj" name="assertj-core" rev="1.6.0" conf="default" />
        <dependency org="com.github.kevinsawicki" name="http-request" rev="5.5" conf="default" />
        <dependency org="com.googlecode.java-diff-utils" name="diffutils" rev="1.3.0" conf="default" />
        <dependency org="io.restx" name="restx-server-jetty8" rev="0.35" conf="test->default" />
    </dependencies>
</ivy-module>
