<ivy-module version="2.0" xmlns:ea="http://www.easyant.org">
    <info organisation="io.restx" module="restx-validation" revision="0.35" status="integration">
        <ea:build organisation="org.apache.easyant.buildtypes" module="build-std-java" revision="0.9"
            compile.java.source.version="1.7"
            compile.java.target.version="1.7"
        />
    </info>
    <configurations>
        <conf name="default"/>
        <conf name="runtime"/>
        <conf name="test"/>
    </configurations>
    <publications>
        <artifact type="jar"/>
    </publications>
    <dependencies>
        <dependency org="io.restx" name="restx-factory" rev="latest.integration" conf="default" />
        <dependency org="org.hibernate" name="hibernate-validator" rev="5.0.1.Final" conf="default" />
        <dependency org="javax.el" name="el-api" rev="2.2" conf="default" />
        <dependency org="org.glassfish.web" name="el-impl" rev="2.2" conf="runtime->default" />
    </dependencies>
</ivy-module>
